# Generated by Django 6.0.4 on 2026-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yangi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("brend", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("color", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
